using System;
using Xamarin.Forms;
namespace S2KLogin
{
	public   interface S2KInterface
	{
		 
		String authLogin(String jarg1, String jarg2);
		String authDeviceRegister(String jarg1); 		String authRegisterConfirm(); 		String requestWholeData(String jarg1, String jarg2); 		String requestUserConfirm(int jarg1); 		String requestLatestPushData(); 		void clearInternalData(); 		String isAvailable(); 		void writePassword(String jarg1); 		String comparePassword(String jarg1); 		String readPassword(); 		String readIsPWOn(); 		void writeIsPWOn(int jarg1); 		String refreshData(String jarg1); 		String getEncData(); 		String writeModeChange(int jarg1); 		String readMode(); 		String userConfirmType2(String jarg1, String jarg2); 		String remains(); 		String enterUUID(String jarg1); 		String call_registerDeviceAndUserInfo(String jarg1, String jarg2, String jarg3, String jarg4); 		String call_registerFinAccountCard(String jarg1, String jarg2); 		String requestResignDevice(); 		String registerContentOfEFT(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6); 		String requestListOfEFT(String jarg1); 		String registerPurchaseData(String jarg1, String jarg2, String jarg3); 		String requestStateOfFinAccountCard(String jarg1, String jarg2); 		String requestEFTSuggestion(); 		String requestChangeEFTName(String jarg1, String jarg2, String jarg3); 		String registerIABState(String jarg1, String jarg2); 		String requestResignService(); 		String requestRegisteredFinAccountCard(); 		String requestUnregisterFinAccountCard(String jarg1, String jarg2, String jarg3); 		String registerUserMessage(String jarg1); 		String requestUserMessageList(); 		String registerDeviceChange(String jarg1, String jarg2, String jarg3); 		String makeSignSession(); 		String registerDeviceInfo(); 		String pc_registerDeviceChange(String jarg1, String jarg2, String jarg3); 		String pc_requestTempPassword(String jarg1, String jarg2, String jarg3); 		String pc_registerDeviceAndUserInfo(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6); 		String pc_requestRegisteredList(); 		String pc_registerPCState(String jarg1, String jarg2, String jarg3); 		String pc_requestNoticeList(); 		String pc_requestQNAList(); 		String pc_registerQuestion(String jarg1); 		String pc_requestLatestVersion(); 		String pc_requestReleaseDevice(); 		String pc_brokeService(String jarg1, String jarg2); 		String readUserInfo(); 
	}
}
